[target.aarch64-unknown-linux-gnu]
image="xtpost/aarch64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
image="xtpost/armv7-unknown-linux-gnueabihf"

[target.x86_64-unknown-linux-gnu]
image="xtpost/x86_64-unknown-linux-gnu"
